/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	versioned "/home/gsanti/myLiqo/foreign_cluster_connector/pkg/client/clientset/versioned"
	internalinterfaces "/home/gsanti/myLiqo/foreign_cluster_connector/pkg/client/informers/externalversions/internalinterfaces"
	apiv1beta1 "/home/gsanti/myLiqo/foreign_cluster_connector/pkg/client/listers/api/v1beta1"
	context "context"
	time "time"

	foreignclusterconnectorapiv1beta1 "github.com/Gabbe64/foreign_cluster_connector/api/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ForeignClusterConnectionInformer provides access to a shared informer and lister for
// ForeignClusterConnections.
type ForeignClusterConnectionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv1beta1.ForeignClusterConnectionLister
}

type foreignClusterConnectionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewForeignClusterConnectionInformer constructs a new informer for ForeignClusterConnection type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewForeignClusterConnectionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredForeignClusterConnectionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredForeignClusterConnectionInformer constructs a new informer for ForeignClusterConnection type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredForeignClusterConnectionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1beta1().ForeignClusterConnections(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1beta1().ForeignClusterConnections(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1beta1().ForeignClusterConnections(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1beta1().ForeignClusterConnections(namespace).Watch(ctx, options)
			},
		},
		&foreignclusterconnectorapiv1beta1.ForeignClusterConnection{},
		resyncPeriod,
		indexers,
	)
}

func (f *foreignClusterConnectionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredForeignClusterConnectionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *foreignClusterConnectionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&foreignclusterconnectorapiv1beta1.ForeignClusterConnection{}, f.defaultInformer)
}

func (f *foreignClusterConnectionInformer) Lister() apiv1beta1.ForeignClusterConnectionLister {
	return apiv1beta1.NewForeignClusterConnectionLister(f.Informer().GetIndexer())
}
