apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: liqo-shortcutmanager
    app.kubernetes.io/name: liqo-shortcutmanager
    app.kubernetes.io/managed-by: kustomize
  name: liqo-shortcutmanager-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: liqo-shortcutmanager
  namespace: liqo-shortcutmanager-system
  labels:
    control-plane: liqo-shortcutmanager
    app.kubernetes.io/name: liqo-shortcutmanager
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: liqo-shortcutmanager
      app.kubernetes.io/name: liqo-shortcutmanager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: liqo-shortcutmanager
      labels:
        control-plane: liqo-shortcutmanager
        app.kubernetes.io/name: liqo-shortcutmanager
    spec:
      # TODO(user): Uncomment the following code to configure the nodeAffinity expression
      # according to the platforms which are supported by your solution.
      # It is considered best practice to support multiple architectures. You can
      # build your manager image using the makefile target docker-buildx.
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #           - key: kubernetes.io/arch
      #             operator: In
      #             values:
      #               - amd64
      #               - arm64
      #               - ppc64le
      #               - s390x
      #           - key: kubernetes.io/os
      #             operator: In
      #             values:
      #               - linux
      securityContext:
        # Projects are configured by default to adhere to the "restricted" Pod Security Standards.
        # This ensures that deployments meet the highest security requirements for Kubernetes.
        # For more details, see: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: ghcr.io/Gabbe64/liqo-shortcutmanager:latest
        imagePullPolicy: IfNotPresent
        name: liqo-shortcutmanager
        ports: []
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts: []
      volumes: []
      serviceAccountName: liqo-shortcutmanager
      terminationGracePeriodSeconds: 10
