apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: liqo-shortcutmanager
    app.kubernetes.io/managed-by: kustomize
  name: liqo-shortcutmanager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: liqo-shortcutmanager-role
subjects:
- kind: ServiceAccount
  name: liqo-shortcutmanager
  namespace: liqo-shortcutmanager-system
