apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: liqo-shortcutmanager
    app.kubernetes.io/managed-by: kustomize
  name: liqo-shortcutmanager
  namespace: liqo-shortcutmanager-system
