/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	scheme "/home/gsanti/myLiqo/foreign_cluster_connector/pkg/client/clientset/versioned/scheme"
	context "context"

	apiv1beta1 "github.com/Gabbe64/foreign_cluster_connector/api/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ForeignClusterConnectionsGetter has a method to return a ForeignClusterConnectionInterface.
// A group's client should implement this interface.
type ForeignClusterConnectionsGetter interface {
	ForeignClusterConnections(namespace string) ForeignClusterConnectionInterface
}

// ForeignClusterConnectionInterface has methods to work with ForeignClusterConnection resources.
type ForeignClusterConnectionInterface interface {
	Create(ctx context.Context, foreignClusterConnection *apiv1beta1.ForeignClusterConnection, opts v1.CreateOptions) (*apiv1beta1.ForeignClusterConnection, error)
	Update(ctx context.Context, foreignClusterConnection *apiv1beta1.ForeignClusterConnection, opts v1.UpdateOptions) (*apiv1beta1.ForeignClusterConnection, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, foreignClusterConnection *apiv1beta1.ForeignClusterConnection, opts v1.UpdateOptions) (*apiv1beta1.ForeignClusterConnection, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1beta1.ForeignClusterConnection, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1beta1.ForeignClusterConnectionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1beta1.ForeignClusterConnection, err error)
	ForeignClusterConnectionExpansion
}

// foreignClusterConnections implements ForeignClusterConnectionInterface
type foreignClusterConnections struct {
	*gentype.ClientWithList[*apiv1beta1.ForeignClusterConnection, *apiv1beta1.ForeignClusterConnectionList]
}

// newForeignClusterConnections returns a ForeignClusterConnections
func newForeignClusterConnections(c *ApiV1beta1Client, namespace string) *foreignClusterConnections {
	return &foreignClusterConnections{
		gentype.NewClientWithList[*apiv1beta1.ForeignClusterConnection, *apiv1beta1.ForeignClusterConnectionList](
			"foreignclusterconnections",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1beta1.ForeignClusterConnection { return &apiv1beta1.ForeignClusterConnection{} },
			func() *apiv1beta1.ForeignClusterConnectionList { return &apiv1beta1.ForeignClusterConnectionList{} },
		),
	}
}
